# crafting
graphite-press: 3
multi-press: 15
silicon-smelter: 6
kiln: 9
plastanium-compressor: 16
phase-weaver: 23
alloy-smelter: 22
cryofluidmixer: 22
blast-mixer: 15
pyratite-mixer: 6
melter: 14
separator: 18
spore-press: 9
pulverizer: 25
coal-centrifuge: 13
incinerator: 10

# Sandbox
power-void: 1
power-source: 1
item-source: 1
item-void: 1
liquid-source: 1
message: 5

# Defence
scrap-wall: 1
scrap-wall-large: 1
scrap-wall-huge: 1
scrap-wall-gigantic: 1
thruster: 1
copper-wall: 3
copper-wall-large: 6
titanium-wall: 6
titanium-wall-large: 8
thorium-wall: 8
thorium-wall-large: 12
phase-wall: 16
phase-wall-large: 20
surge-wall: 12
surge-wall-large: 16
door: 9
door-large: 12
mender: 8
mend-projector: 16
overdrive-projector: 27
force-projector: 20
shock-mine: 16

# Distribution
conveyor: 1
titanium-conveyor: 7
armored-conveyor: 15
junction: 1
bridge-conveyor: 5
phase-conveyor: 20
sorter: 5
router: 3
distributor: 5
overflow-gate: 7
mass-driver: 30

# Liquid
mechanical-pump: 3
rotary-pump: 17
thermal-pump: 23
conduit: 9
pulse-conduit: 17
liquid-router: 14
liquid-tank: 17
liquid-junction: 11
bridge-conduit: 14
phase-conduit: 23

# Power
power-node: 3
power-node-large: 7
surge-tower: 20
battery: 5
battery-large: 15
combustion-generator: 6
thermal-generator: 16
turbine-generator: 12
differential-generator: 23
rtg-generator: 40
solar-panel: 7
solar-panel-large: 11
thorium-reactor: 30
impact-reactor: 50

# Production
mechanical-drill: 1
pneumatic-drill: 6
laser-drill: 12
blast-drill: 16
water-extractor: 16
cultivator: 12
oil-extractor: 20

# Storage
vault: 23
container: 10
unloader: 13

# Turrets
duo: 1
scatter: 3
scorch: 5
hail: 8
wave: 13
lancer: 15
arc: 10
swarmer: 28
salvo: 12
fuse: 25
ripple: 20
cyclone: 30
spectre: 40
meltdown: 50

# Units
draug-factory: 6
spirit-factory: 10
phantom-factory: 16
command-center: 14
wraith-factory: 17
ghoul-factory: 20
revenant-factory: 25
dagger-factory: 8
crawler-factory: 13
titan-factory: 22
fortress-factory: 25
repair-point: 20

# Upgrade
dart-mech-pad: 10
delta-mech-pad: 15
tau-mech-pad: 20
omega-mech-pad: 25
javelin-ship-pad: 20
trident-ship-pad: 25
glaive-ship-pad: 30
