owner:
  - *
admin:
  inheritance: new_admin
  permission:
    - essentials.color
    - essentials.difficulty
    - essentials.save
    - essentials.tempban
new_admin:
  interitance: global
  permission:
    - essentials.kill
    - essentials.me
    - essentials.tpp
global:
  inheritance: guest
  permission:
    - essentials.ch
    - essentials.event
    - essentials.getpos
    - essentials.info
    - essentials.logout
    - essentials.maps
    - essentials.motd
    - essentials.status
    - essentials.suicide
    - essentials.time
    - essentials.vote
guest:
  permission:
    - essentials.login
    - essentials.register