owner:
  inheritance: admin
  permission:
    - jump
    - jumpcount
    - jumptotal
    - kickall
    - test
    - setperm
admin:
  inheritance: newadmin
  permission:
    - color
    - difficulty
    - save
    - tempban
    - save
    - spawn
newadmin:
  inheritance: default
  permission:
    - kill
    - me
    - tpp
    - team
    - tempban
    - tpp
default:
  permission:
    - ch
    - changepw
    - event
    - getpos
    - info
    - login
    - logout
    - maps
    - me
    - motd
    - register
    - status
    - suicide
    - time
    - tp
    - tppos
    - tr
    - vote